language: go
notifications:
  email: false
env:
- DEP_VERSION="0.4.1"
before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64
  -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- GO111MODULE=on go get github.com/golangci/golangci-lint/cmd/golangci-lint@v1.24.0
install:
- dep ensure
before_script:
- make lint
script:
  make test
