version: '3'
services:
  app:
    build: .
    environment:
      - S3_EXTENSIONS_BUCKET_HOST=brave-core-ext-dev.s3.bravesoftware.com
      - S3_EXTENSIONS_BUCKET_HOST_TOR=tor-dev.bravesoftware.com
    ports:
      - "80:8192"
